/*
 js-cookie v3.0.1 | MIT */
'use strict';const constants_system={isMobile:/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isDarkMode:window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches,isBrowser:"object"===typeof window&&"object"===typeof document,isHttps:"https:"===location.protocol},constants_app={name:"learning-style",title:"Learning-Style",isStatic:!0,version:"16.12.2021",state:"development",lang:"en",keyboard:constants_system.isMobile?1:0};
constants_system.infoString=`state: ${constants_app.state}, version: ${constants_app.version} (${constants_app.isStatic?"static":"api"}), `;constants_system.infoString+=constants_system.isMobile?"mobile OS: ":"OS: ";constants_system.infoString+=navigator.userAgent;constants_system.infoString+=constants_system.isDarkMode?", DarkMode":"";document.getElementsByClassName("version")[0].textContent=constants_system.infoString;
const CSS_COLORS=[{name:"white",colors:["white"]},{name:"black",colors:["black"]},{name:"dark",colors:["#373737"]},{name:"green",colors:["#28a745"]},{name:"red",colors:["#dc3545"]},{name:"orange",colors:["#ff6600"]},{name:"-",colors:[""]},{name:"gray-dark",colors:["#333333"]},{name:"gray",colors:["#646464"]},{name:"gray-light",colors:["#959595"]},{name:"gray-text",colors:["#cacaca"]},{name:"gray-line",colors:["#dedede"]},{name:"--",colors:[""]},{name:"light-red",colors:["#feaec8"]},{name:"light-blue",
colors:["#99d9e9"]},{name:"light-yellow",colors:["#efe4b0"]},{name:"light-pink",colors:["#c7bfe6"]},{name:"---",colors:[""]},{name:"links",colors:["#0275d8"]},{name:"color-bg",colors:["#f1f1f1"]},{name:"color-bg-hover",colors:["#ddd"]},{name:"hover",colors:["#1795ec"]},{name:"active",colors:["#4299E1"]},{name:"border",colors:["#ccc"]},{name:"submit",colors:["#4caf50"]},{name:"submit-hover",colors:["#45a049"]},{name:"logo",colors:["#517cc6"]},{name:"----",colors:[""]},{name:"success",colors:["#c1ffde",
"#c1ffde","#dbfff8"]},{name:"danger",colors:["#ffcede"]},{name:"error",colors:["#e00"]},{name:"info",colors:["#4299E1"]},{name:"alert-success",colors:["#00A4A6"]}],constants_server={local:"http://192.168.0.52:9999",relative:".",url:".",api:"./api",json:"./json"},constants_dom={pageheader:{tagName:"header"},menu:{className:"navbar"},aside:{tagName:"aside"},article:{tagName:"article"},header:{id:"header"},control:{id:"control"},content:{id:"content"},messages:{id:"messages"},bottom:{id:"bottom"},cdate:{id:"cdate"},
breadcrumb:{className:"breadcrumb",tagName:"ul"},subject:{className:"subject"},notify:{className:"notify-box"}},ms={en:{}};ms.en.input={};ms.en.bnt={};ms.en.quiz={};ms.en.keyboard={};ms.en.server={};ms.de={};ms.de.input={};ms.de.bnt={};ms.en.input.again="Write this again.";ms.de.input.again="Schreiben Sie das Wort noch einmal auf.";ms.en.input.placeholder="Write this ..";ms.en.bnt.validate="Validate";ms.de.bnt.validate="Bestätigen";ms.en.bnt.clear="Clear";ms.de.bnt.clear="löschen";
ms.en.bnt.view="view";ms.de.bnt.view="ansehen";ms.en.keyboard.off="keyboard: system";ms.en.keyboard.static="keyboard: virtual";ms.en.keyboard.byString="keyboard: virtual (auto)";ms.en.quiz.server="Server validation is not supported on static version.";ms.en.quiz.corect="Not found correct answers.";ms.en.server.required="Server side required!";
const CS={app:constants_app,system:constants_system,server:constants_server,dom:constants_dom,colors:CSS_COLORS,msg:ms.en},dom={get(a){return"string"===typeof a?document.getElementById(a):document.body.contains(a)?a:null},setOptions(a,b){if("string"===typeof b)a.setAttribute("class",b);else for(const [c,d]of Object.entries(b))"textContent"===c||"className"===c||"value"===c?a[c]=d:a.setAttribute(c,d)},element(a,b,c){a=document.createElement(a);b.appendChild(a);c&&this.setOptions(a,c);return a},node(a,
b){a=document.createTextNode(a);b.appendChild(a);return a},text(a,b,c,d){a=this.element(a,b,0);a.textContent=c;d&&this.setOptions(a,d);return a},removeAll(a){a&&(a.innerHTML="")},remove(a){return a?a.parentNode?a.parentNode.removeChild(a):0:0},svgUse(a,b,c,d,e,f="img"){const g=document.createElementNS("http://www.w3.org/2000/svg","svg"),h=document.createElementNS("http://www.w3.org/2000/svg","use");c&&g.setAttributeNS(null,"class",c);g.setAttributeNS(null,"width",d);g.setAttributeNS(null,"height",
e||d);g.setAttributeNS(null,"role",f);h.setAttributeNS(null,"href",b);g.appendChild(h);a.appendChild(g);return g}};
class ScopeCounter{constructor(a=0,b,c){this.min=a;this.max=b;this.stack=[];this.numbers=[];this.waitings=[];this.counts=[];this.DEFAULT_WAITING=5;this.shuffle=c;this.state={}}getValue(){return this.isNumber(this.state.value)?this.state.value:this.stack.slice(-1)[0]}next(){this.isEmpty()&&this.reset();if(this.hasNext()){if(this.isWaiting())return this.state.value=this.waitings.shift(),this;this.stack.push(this.numbers.splice(this.shuffle?this.randomIndex():0,1)[0])}this.resetState();return this}previous(){if(this.hasPrevious()){const a=
this.getValue();1<this.stack.length&&!this.isNumber(this.state.value)&&(this.stack.pop(),this.numbers.unshift(a));this.removeFromWaiting(a);this.removeFromWaiting(this.stack.slice(-1)[0])}this.resetState();return this}removeFromWaiting(a){this.waitings.length&&(a=this.waitings.indexOf(a),-1<a&&(this.waitings.splice(a,1),this.counts.splice(a,1)))}repeat(a){if(this.hasPrevious()){const b=this.getValue();this.waitings.includes(b)?this.counts[this.waitings.indexOf(b)]=a||this.DEFAULT_WAITING:(this.waitings.push(b),
this.counts.push(a||this.DEFAULT_WAITING))}this.state.repeat=!0;return this}getPreviousCount(){return this.stack.length-this.waitings.length}isWaiting(){if(this.waitings.length&&(this.counts[0]--,1>this.counts[0]||!this.numbers.length))return this.counts.shift(),!0}skip(){this.state.repeat&&this.removeFromWaiting(this.waitings.slice(-1)[0]);return this.next()}randomIndex(){return Math.floor(Math.random()*this.numbers.length)}hasNext(){return this.numbers.length||this.waitings.length}hasPrevious(){return this.stack.length}isNumber(a){return"number"===
typeof a}isValid(){return this.isNumber(this.max)&&-1<this.min&&this.max>this.min}isEmpty(){return!this.numbers.length&&!this.waitings.length&&!this.stack.length}isDone(){return!this.numbers.length&&!this.waitings.length&&this.stack.length}resetState(){for(const a of Object.keys(this.state))this.state[a]=null}reset(a){this.max=this.isNumber(a)?a:this.max;this.stack.length=0;this.numbers.length=0;this.waitings.length=0;this.counts.length=0;this.resetState();if(this.isValid()){a=this.min;for(let b=
this.min;b<this.max;b++)this.numbers[a++]=b}}}function SimpleCounter(a=0){let b=a;return{value(){return b},next(){return++b},back(){return b=b>a?b-1:a},reset(){b=a}}}
class Flags{static set(a,b){return a|b}static clear(a,b){return a&~b}static toggle(a,b){return a^b}static isTrue(a,b){return 0<(a&b)}static isFalse(a,b){return 0===(a&b)}static toBits(a){return 1<<a}static toNumber(a){return a.reduce((b,c,d)=>b+(c?1<<d:0),0)}static toIndex(a){let b=0;0!==(a&4294901760)&&(a>>>=16,b=16);256<=a&&(a>>>=8,b+=8);16<=a&&(a>>>=4,b+=4);4<=a&&(a>>>=2,b+=2);return b+(a>>>1)}static toArray(a,b){return Array.from({length:b},(c,d)=>Flags.isTrue(a,Flags.toBits(d)))}static byLength(a){let b=
0;for(let c=0;c<a;c++)b|=1<<c;return b}}
class ArrayOfFlags{constructor(){this.length=this.number=0}get length(){return this._length}set length(a){this._length=a;this.number=Flags.byLength(a)}getIndex(a){return Flags.isTrue(this.number,Flags.toBits(a))}setIndex(a,b){this.number=b?Flags.set(this.number,Flags.toBits(a)):Flags.clear(this.number,Flags.toBits(a))}toggle(a){this.number=Flags.toggle(this.number,Flags.toBits(a))}get array(){return Flags.toArray(this.number,this.length)}set array(a){this._length=a.length;this.number=Flags.toNumber(a)}}
const getRandomUUID=a=>a?(a^16*Math.random()>>a/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,generateRandomUUID),numbers={getRandomInt(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a)+a)},getRandomUUID,timer:{start(){return new Date},stop(a,b,c,d,e){a=new Date-a;b=this.text(a,b,c,d,e);return{diff:a,text:b}},text(a,b,c,d,e){b=b?`${Math.floor(a/36E5)}:`:"";b+=`${Math.floor(a%36E5/6E4).toLocaleString("de-DE",{minimumIntegerDigits:2})}`;b+=d?`:${Math.floor(a%
6E4/1E3).toLocaleString("de-DE",{minimumIntegerDigits:2})}`:"";return b+=d&&e?`.${Math.floor(a%1E3).toLocaleString("de-DE",{minimumIntegerDigits:4,useGrouping:!1})}`:""}}},objects={isObject(a){return a&&"object"===typeof a&&!Array.isArray(a)},isArray(a){return a&&Array.isArray(a)},assign:object_assign};
function object_assign(a,...b){let c;for(const d of b)for(const e of Object.keys(d||{}))b=d[e],c=a[e],objects.isObject(b)?(!c&&objects.isObject(b)&&Object.assign(a,{[e]:{}}),object_assign(a[e],b)):objects.isArray(b)?a[e]=b.slice():Object.assign(a,{[e]:b});return a}
const charsIgnore=".,:;_?!`".split(""),strings={isEmpty(a){return!a||!a.length},isBlank(a){return!a||!a.trim().length},isValid(a){return"string"===typeof a&&a.trim().length},clear(a){return(a||"").trim().replace("  "," ")},mask(a,b){let c;return this.split((a||"").toLowerCase()).map(d=>{c=d.length;return 3<c?d.substr(0,1)+b.repeat(c-2)+d.slice(-1):2<c?d.substr(0,1)+b.repeat(c-1):d}).join("")},split(a){return this.clear(a).split(/([ .,:;_\-?!'`]+)/)},removeHTML(a){return a.replace(/&/g,"").replace(/</g,
"").replace(/"/g,"").replace(/'/g,"").replace(/`/g,"")},utf8_to_b64(a){return window.btoa(unescape(encodeURIComponent(a)))},b64_to_utf8(a){return decodeURIComponent(escape(window.atob(a)))}},inMemoryRepository=function(){const a={};return{existsByName(b){return a.hasOwnProperty(b)},getByName(b){return a[b]},save(b,c){a[b]=c;return this.getByName(b)},remove(b){this.existsByName(b)&&delete a[b]}}}(),cookie={encode(a){return encodeURIComponent(a).replace(/%(2[346B]|5E|60|7C)/g,decodeURIComponent).replace(/[()]/g,
escape)},props(a){return"; expires\x3d"+(new Date(Date.now()+864E5*(a||365))).toUTCString()+"; path\x3d/; SameSite\x3dLax"},getItem(a){const b=(document.cookie||"").split("; "),c=this.encode(a)+"\x3d";return(a=b.find(d=>0===d.indexOf(c)))?strings.b64_to_utf8(a.substring(c.length)):null},setItem(a,b){a=this.encode(a)+"\x3d";return document.cookie=a+strings.utf8_to_b64(b)+this.props()}},localRepository=function(){const a=CS.system.isMobile||!localStorage?cookie:localStorage;return{getItem(b){return a.getItem(b)},
setItem(b,c){a.setItem(b,c)}}}(),repository=function(){const a=CS.app.isStatic,b=CS.server.json;return{async getByName(c){return await (a?this.fetchStatic:this.fetchApi)(c)},async fetchStatic(c){c=b+(c.startsWith("/")?"":"/")+c+".json";return await (await fetch(c)).json()},async fetchApi(c){return await sendRequest(c)}}}();
class Data{async getJson(a,b,c){let d;if(b&&(d=this.getCashable(a)))return d;d=await repository.getByName(a);if(!d)return null;c&&(d=this.adapt(d));b&&(d=inMemoryRepository.save(a,d));return d}async getJsonWithPayload(a,b){return await postData(a,b)}getCashable(a){if(inMemoryRepository.existsByName(a))return console.debug("cashed: "+a+".json"),inMemoryRepository.getByName(a)}adapt(a){return dataAdapter(a)}}
function dataAdapter(a){const b=a.props.adapter,c=Object.entries(a.props).filter(d=>d[0].startsWith("label")).sort((d,e)=>d[0].localeCompare(e[0])).map(d=>d[1]);a.labels=c;a.props.card=parseInt(a.props.card);if(!isNaN(b))if("0"===b)a.data=arrayToMatrix(a.data,c.length);else{const d=getAdapter(a,parseInt(b));a.data=a.data.map(e=>d(e))}a.state={counts:Array(a.data.length).fill(0),status:!1,rows:a.data.length,row:0,tabs:Array(c.length).fill(!0),card:a.props.card};a.state.tabs[a.state.card]=!1;return a}
function getAdapter(a,b){const c=a.labels.map(d=>d.toLowerCase());return[arrayToMatrix,function(d){return[d[0][c[0]],d[1][c[1]],d[0][c[2]]+" - "+d[1][c[2]],d.slice(-1)[0]]}][b]}function arrayToMatrix(a,b){const c=[];let d=0;for(let e=0;e<a.length;e+=b)c[d++]=a.slice(e,e+b);return c}function requestString(a){return CS.server.api+(a.startsWith("/")?"":"/")+a}
async function sendRequest(a,b,c){try{return await (await fetch(requestString(a),{method:b||"GET",headers:c?{"Content-Type":"application/json"}:void 0,body:c}).then(d=>d)).json()}catch(d){return{error:d.message||"Unknown error"}}}
async function postData(a,b){return fetch(requestString(a),{method:"POST",mode:"cors",cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json","Accept-Language":CS.app.lang},redirect:"follow",referrerPolicy:"no-referrer",body:JSON.stringify(b)}).then(c=>{c.headers.get("content-length");c.headers.get("content-type");if(c.redirected)window.location.assign(c.url);else return c.text()}).then(c=>{try{return JSON.parse(c)}catch(d){return c}})}
const factory=function(){const a={},b={},c=d=>"function"===typeof d?d.name||d.constructor.name:d;return{addClass:(d,e,f)=>{const g=c(d);a[g]={Clazz:"function"===typeof d?d:void 0,parent:e,path:f}},addInstance:(d,e)=>{d=c(d);b[d.toLowerCase()]=e},addEvent:(d,e,f)=>{d=c(d);a[d].eventType=e;a[d].event=f},getInstance,instance:d=>b[c(d).toLowerCase()],props:d=>a[c(d)]}}(),routes=[{path:"/",name:"home",title:CS.app.title,subject:"Home",render:home},{path:"/cards",name:"cards",title:"Cards",subject:"Cards",
init:()=>router.index=1,render:defaultRender},{path:"/quizzes",name:"quizzes",title:"Quiz",subject:"Quiz",init:()=>router.index=2,render:defaultRender},{path:"/maps",name:"maps",title:"Maps",subject:"Maps",init:()=>router.index=3,render:defaultRender},{path:"/login",title:"Login"},{path:"/register",title:"Register"}];
async function home(){router.index=0;document.title=routes[router.index].title;navigation.top.navigateByIndex(1);page.blank();await page.renderContent(debugContent);await topics.render(routes[1].name)}async function defaultRender(){document.title=routes[router.index].title;navigation.top.navigateByIndex(router.index);page.blank();await page.renderContent(debugContent);await topics.render(routes[router.index].name)}
function debugContent(a){dom.text("small",a,"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatem, quibusdam dolores magni eveniet reiciendis fuga illum ad. \n    Harum molestias dolorum deserunt repudiandae molestiae in aut dolorem vitae ducimus sint, illum eum tenetur minima quo dignissimos? \n    Dolorum ad rerum adipisci dolore dignissimos deleniti facere, natus maxime voluptatum veniam soluta ab placeat? Incidunt laborum tempore \n    necessitatibus esse, officia est nemo rerum placeat consectetur atque suscipit modi animi dignissimos eos obcaecati, iste et illo saepe numquam \n    deleniti omnis iusto perferendis distinctio! Soluta maiores adipisci ipsum sint beatae earum ea. Minus dolore molestiae, cupiditate fuga quod, \n    voluptates, nulla consequuntur autem ex facere animi ducimus.")}
class Router{constructor(){Router.instance=this;this.index=0;this.routes=routes;this.state={page:-1}}setIndex(a){this.index=Router.getIndex(a);this.route=this.getRoute()}getRoute(){return this.routes[this.index]}static isValid(a){return Number.isInteger(a)&&-1<a&&a<routes.length}async navigate(a,b,c){c&&c.username&&(CS.app.username=c.username);if(c&&c.page)await this.navigate(c.page,c.id,null);else{var d=null===a?this.index:Router.getIndex(a);c=d!==this.state.page;var e=b!==this.state.id;if(c||e)this.setIndex(d),
this.state={page:this.index,id:b},b="?page\x3d"+this.index+(b?"\x26id\x3d"+b:""),window.history.pushState(Object.assign({},this.state),this.route.title,b),await Router.update(null,this.state,(c?1:0)+(e?2:0)+(null===a?4:0))}}urlSearchParams(){const a=new URLSearchParams(window.location.search),b={};a.has("page")&&(b.page=a.get("page"));a.has("id")&&(b.id=a.get("id"));a.has("username")&&(b.username=a.get("username"));return b}static getIndex(a){let b=0;if("number"===typeof a)b=a;else if("string"===
typeof a)if(isNaN(a)){const c=a.trim().toLowerCase();b=routes.findIndex(d=>d.path===(c.startsWith("/")?"":"/")+c)}else b=a^0;return Router.isValid(b)?b:0}static async update(a,b,c){let d=b=null;const e=Router.instance,f=e.state;if(a){if(!a.state)return;const {page:g,id:h}=a.state;b=g!==f.index;d=h!==f.id;b&&e.setIndex(g);f.page=g;f.id=h}c&&(b=1===c||3===c,d=1<c);a=d&&!f.id;if(b||a)"function"===typeof e.route.init&&e.route.init(),"function"===typeof e.route.render&&await e.route.render(),a&&(Router.exercise.id=
null,Router.exercise.focusLink());d&&f.id&&await Router.exercise.render(f.id)}static async navigateEvent(a){a.target&&a.target.hasAttribute("key")&&await Router.instance.navigate(parseInt(a.target.getAttribute("key")),null,null)}}window.onpopstate=async function(a){await Router.update(a)};
class Page{constructor(){Page.init();this.elements=Page.elements}static init(){const a=Page.elements;a.pageheader=document.getElementsByTagName(a.pageheader.tagName)[0];a.menu=document.getElementsByClassName(a.menu.className)[0];a.aside=document.getElementsByTagName(a.aside.tagName)[0];a.article=document.getElementsByTagName(a.article.tagName)[0];a.header=document.getElementById(a.header.id);a.control=document.getElementById(a.control.id);a.content=document.getElementById(a.content.id);a.messages=
document.getElementById(a.messages.id);a.bottom=document.getElementById(a.bottom.id);a.cdate=document.getElementById(a.cdate.id);a.cdate.textContent=`${(new Date).getFullYear()}`;const b=dom.element("div",a.header,"row"),c=dom.element("div",a.header,"row");dom.element("hr",a.header);a.breadcrumb=dom.element(a.breadcrumb.tagName,b,a.breadcrumb.className);a.subject=dom.element("div",c,a.subject.className);a.notify1=dom.element("div",b,CS.dom.notify.className);a.notify2=dom.element("div",c,CS.dom.notify.className)}static reset(){notify.clear();
this.elements.pageheader.removeAttribute("style");this.elements.menu.removeAttribute("style");this.elements.aside.removeAttribute("style");this.elements.article.removeAttribute("style");this.elements.control.innerHTML="";this.elements.content.innerHTML="";this.elements.content.removeAttribute("style");this.elements.messages.innerHTML="";this.elements.bottom.innerHTML=""}blank(a){const {name:b,category:c}=a||{};Page.reset();renderBreadcrumb(c);renderSubject(this.elements.subject,b||router.route.subject,
a)}play(a){notify.clear();this.elements.pageheader.style.display=a?"none":"";this.elements.menu.style.display=a?"none":"";this.elements.aside.style.display=a?"none":"";a&&(this.elements.content.style.display="");this.active=a}async renderContent(a,b){await a(this.elements.content,b)}}Page.elements=Object.assign({},CS.dom);
function renderBreadcrumb(a){const b=[];0<router.index&&(b.push({href:"./",textContent:router.routes[0].subject}),b.push({key:router.index,textContent:router.route.subject}));breadcrumb.render(b);breadcrumb.addTopic(a)}
function renderSubject(a,b,c){const d=[];a.innerHTML="";dom.text("h3",a,b);if(c){var e=[c.source,c.sourceUrl,c.author,c.authorUrl];b=e.map(f=>f?f.split(";"):[]);c=b.map(f=>f.length).reduce((f,g)=>f+g,0);if(8<=c)for(e=0;e<c/4;e++)d.push([b[0][e],b[1][e],b[2][e],b[3][e]]);else d.push(e)}for(b=0;b<d.length;b++){const [f,g,h,k]=d[b];c=dom.element("small",a);f&&(dom.node((0<b?"; ":"")+"source: ",c),dom.text("a",c,f,formatLink(g)));h&&(dom.node(f?", author: ":"author: ",c),dom.text("a",c,h,formatLink(k)))}}
function formatLink(a){const b={};b.href=a||"#";["#","/","\\"].includes(b.href)||(b.target="_blank");return b}const EXERCISE={cashable:!0,classNameFocus:"focus",indexes:["-",{Clazz:"Flashcards",adaptable:!0},{Clazz:"Quizzes"},{Clazz:"Maps"}]};
class Exercise{constructor(){Exercise.instance=this;Exercise.current=void 0}async render(a){this.reset();this.id=parseInt(a);await router.navigate(router.index||1,this.id);a=EXERCISE.indexes[router.index];Exercise.current=await factory.getInstance(a.Clazz);Exercise.current.controller=this;this.json=await data.getJson(router.route.path+"/"+this.id,EXERCISE.cashable,a.adaptable);this.key="learning-style/"+this.json.exercise.path;await page.blank(this.json.exercise);await Exercise.current.render(this.json);
this.focusLink()}start(){if(page.active)Exercise.current.stop();else{Exercise.current.startTime=new Date;Exercise.current.start();var a=localRepository.getItem(this.key);if(a&&(a=JSON.parse(a))&&a.games){const {stack:b,success:c,errors:d,timer:e}=a;notify.btn("","successful: "+a.games,()=>{notify.alert("info",`Top result - successes: ( ${c} / ${b} ), errors: ( ${d} ), time: ${numbers.timer.text(e,0,1,1,0)}`)},{hideSvg:!0,button:{tag:"small"}})}}}finish(a){finishExercise(a)}next(){Exercise.current.next()}skip(){Exercise.current.skip()}previous(){Exercise.current.previous()}shuffle(){Exercise.current.toggleShuffle()}reset(){Exercise.current&&
(Exercise.current.stop(),Exercise.current=void 0)}focusLink(){Array.from(document.querySelectorAll("aside a")).forEach(a=>{a.classList.toggle(EXERCISE.classNameFocus,parseInt(a.value)===this.id)})}static controlEvent(a){clickButton(getButtonElement(a.target))}static async renderEvent(a){a.target&&"A"===a.target.tagName&&await Exercise.instance.render(a.target.value)}}function getButtonElement(a){if(a&&"DIV"!==a.tagName)return"BUTTON"===a.tagName?a:getButtonElement(a.parentNode)}
function clickButton(a){if(a){var b=a.getAttribute("id");a=a.getAttribute("key");b?"start"===b?Exercise.instance.start():"back"===b?Exercise.instance.previous():"forward"===b?Exercise.instance.skip():"shuffle"===b&&Exercise.instance.shuffle():a&&(b=parseInt(a),Exercise.current.bar.toggle(b),Exercise.current.list.update(b),Exercise.current.cards.update(b));Exercise.current.resume()}}
function finishExercise(a){const {count:b,stack:c,success:d,errors:e,timer:f}=a;a=Exercise.instance.key;var g=localRepository.getItem(a);notify.msg("success",`${b} | ${c} (${d} successes, ${e} errors, ${f.text} time)`,{prefix:"Done!"});const h=d/c;isNaN(h)||.9>h?(notify.alert("info","Done with less than 90%."),notify.alert("info","Play again ?")):(notify.alert("success","Well done !!!"),notify.alert("info","Play again ?"),g?(g=JSON.parse(g),g.games&&(g.games++,notify.msg("success",`${g.games} ${1===
g.games?"time":"times"}`,{prefix:"Finished: "}),d>g.success&&(g.success=d,notify.alert("success",`Top success points: ${d} !!!`),notify.msg("success",`${d} !!!`,{prefix:"Top success points: "})),f.diff<g.timer&&(g.timer=f.diff,notify.alert("success",`Top time: ${f.text} !!!`),notify.msg("success",`${f.text} !!!`,{prefix:"Top time: "})),e<g.errors&&(g.errors=e,notify.alert("success",`Top errors points: ${d} !!!`),notify.msg("success",`${d} !!!`,{prefix:"Top errors points: "})),localRepository.setItem(a,
JSON.stringify(g)))):localRepository.setItem(a,JSON.stringify({games:1,count:b,stack:c,success:d,errors:e,timer:f.diff})))}const FLASHCARDS={turnsWaitingToRepeat:5};
class Flashcards{constructor(){Flashcards.instance=this;this.btnEdit=()=>notify.btn("info","edit",Flashcards.edit,{hideSvg:!1,button:{svg:{id:"edit",width:14}}});this.btnAdd=notify.create("btnAdd",page.elements.messages,"info","msg",notify.template.msg.button,{capacity:1,button:{func:()=>Flashcards.instance.list.add(),svg:{id:"plus",width:22,height:22,color:"green"}}})}async render(a){this.json=a;this.counter=new ScopeCounter(0,void 0,void 0);this.bar=await factory.getInstance("Bar");this.list=await factory.getInstance("List");
this.cards=await factory.getInstance("Cards");this.input=await factory.getInstance("UserInput");this.tags=await factory.getInstance("Tags");this.bar.render(this.json);this.list.render(this.json);this.input.controller=Flashcards.onTextareaChange;this.tags.render();this.btnEdit()}start(){this.counter.reset(this.json.state.rows);this.bar.start();this.list.remove();this.cards.render(this.json);this.input.render(this.json,null);this.next();page.play(!0)}stop(){page.active&&(this.counter.reset(0),this.bar.stop(),
this.cards.remove(),this.input.remove(),this.list.render(this.json),page.play(!1))}finish(a){this.stop();page.elements.content.style.display="none";this.controller.finish(a)}play(a){let b=!1;this.counter.hasNext()||1!==a&&2!==a?(1===a?b=this.counter.next().getValue():2===a?(this.input.clear(),b=this.counter.skip().getValue()):-1===a?(this.input.stats.change("success",this.input.successCounter.back()),b=this.counter.previous().getValue()||0):0===a&&(b=this.counter.repeat(FLASHCARDS.turnsWaitingToRepeat).getValue()),
this.list.isValidRow(b)?this.input.state.error?(this.cards.setStatus("error",!0),this.cards.update(this.json.state.card),this.input.repeat()):(this.cards.setStatus("error",!1),this.input.stats.change("done",this.counter.getPreviousCount()||1),this.cards.populate(b),this.input.next(),this.bar.row=b+1):console.error("Bad row number!")):this.finish({path:this.json.exercise.path,count:this.counter.getPreviousCount(),stack:this.counter.stack.length,success:this.input.successCounter.value(),errors:this.input.errorsCounter.value(),
timer:numbers.timer.stop(this.startTime,0,1,1,0)})}next(){this.play(1)}skip(){this.play(2)}previous(){this.play(-1)}toggleShuffle(){this.counter.shuffle=!this.counter.shuffle;this.bar.shuffle(this.counter.shuffle);this.counter.reset();this.input.reset();this.next()}static onTextareaChange(a){Flashcards.instance.play(a.state.success?1:0)}resume(){page.active&&this.input.visible(!0)}static edit(){notify.btn("error","save",Flashcards.save);notify.btnAdd("info","add");const a=Flashcards.instance;a.list.render(a.json,
{contenteditable:!0})}static async save(){const a=Flashcards.instance;a.btnEdit();notify.with("btnAdd").clear();var b=[];for(let c of a.list.read())b.push(c.map(d=>strings.removeHTML(d)));if(CS.app.isStatic)a.json.data=b.sort((c,d)=>c[0].localeCompare(d[0])).map(c=>c.slice(1)),a.list.render(a.json),notify.alert("error",CS.msg.server.required);else{if(b=await data.getJsonWithPayload(a.json.exercise.path,{username:CS.app.username||"",data:b}))200===b.status&&(a.json.data=b.data||[]),notify.alert(200===
b.status?"success":"error",b.message);a.list.render(a.json)}}}factory.addClass(Flashcards);const QUIZZES={questions:{className:"questions"},results:{className:"results"},card:{className:"card"},validate:{className:"validate"}};
class Quizzes{constructor(a="content"){this.parent=dom.get(a);this.active=!1;Quizzes.instance=this}async render(a){this.json=a;this.questions=this.json.questions;this.validated=!1;this.correct=this.json.correct;!this.correct&&CS.app.isStatic&&notify.alert("error",CS.msg.quiz.server);this.resultsElement=Quizzes.renderResults(this.parent,QUIZZES.results.className,QUIZZES.card.className);this.resultsElement.firstChild.lastChild.addEventListener("click",function(){Quizzes.instance.validate()});this.resultsElement.firstChild.lastChild.textContent=
CS.msg.bnt.view;this.element=dom.element("ol",this.parent,QUIZZES.questions.className);for(a=0;a<this.questions.length;a++)renderQuestion(this.element,this.questions[a],a);this.bnt=dom.text("button",this.parent,CS.msg.bnt.validate,QUIZZES.validate.className);this.bnt.addEventListener("click",function(){Quizzes.instance.validate()})}static renderResults(a,b,c){a=dom.element("div",a,b);c=dom.element("div",a,c);dom.element("span",c);dom.element("a",c,{href:"#"});return a}stop(){}reset(){this.parent.innerHTML=
"";this.render(this.json)}async validate(){if(Quizzes.instance.validated)Quizzes.instance.reset();else{Quizzes.instance.validated=!0;Quizzes.instance.bnt.textContent=CS.msg.bnt.clear;Quizzes.instance.bnt.classList.toggle("clear",!0);if(!this.correct){var a=await data.getJsonWithPayload(`/quizzes/${this.json.exercise.id}/certification`,{answers:getUserAnswers()});a&&(Quizzes.instance.correct=a.correct)}if(Quizzes.instance.correct){var b=validateQuestions(Quizzes.instance.correct);a=b.length;var c=
b.filter(Boolean).length;0<c&&.5<c/a&&notify.alert("info",`Bravo! ${parseInt(c/a*100)}%`);Array.from(document.getElementsByClassName(QUIZZES.questions.className)[0].children).map((d,e)=>{b[e]&&(d.innerHTML='\x3cli\x3e\x3csvg xmlns\x3d"http://www.w3.org/2000/svg" viewBox\x3d"0 0 24 24" width\x3d"10" height\x3d"10" stroke\x3d"currentColor" stroke-width\x3d"1.5" stroke-linecap\x3d"round" stroke-linejoin\x3d"round" fill\x3d"none" shape-rendering\x3d"geometricPrecision"\x3e\x3cpath d\x3d"M20 6L9 17l-5-5"/\x3e\x3c/svg\x3e\x3c/li\x3e')});
document.getElementsByClassName(QUIZZES.results.className)[0].firstChild.firstChild.textContent=`${c}/${a}`;document.getElementsByClassName(QUIZZES.results.className)[0].firstChild.lastChild.textContent=CS.msg.bnt.clear}else notify.alert("error",CS.msg.quiz.corect)}}}factory.addClass(Quizzes);function renderQuestion(a,b,c){a=dom.element("div",a,"question");dom.text("span",dom.element("li",a),b.text);a=dom.element("div",a);for(let d=0;d<b.answers.length;d++)renderLabel(a,b.answers[d],d,c)}
function renderLabel(a,b,c,d){a=dom.element("label",a,"answer");dom.element("input",a,{name:`question${d}`,type:"checkbox",value:c});dom.text("span",a,b.text)}function validateQuestions(a){const b=document.getElementsByClassName(QUIZZES.questions.className)[0];let c=0;return Array.from(b.children).map(d=>validateQuestion(d,a[c++]))}
function validateQuestion(a,b){a=a.getElementsByTagName("input");let c,d,e,f;for(let g=0;g<a.length;g++)e=a[g],f=e.checked,c=c||f,Flags.isTrue(b,Flags.toBits(g))?e.parentNode.classList.toggle("correct",!0):f&&(e.parentNode.classList.toggle("wrong",!0),d=!0);return!d&&c}
function getUserAnswers(){var a=document.getElementsByClassName(QUIZZES.questions.className)[0];a=Array.from(a.children);const b=Array(a.length);let c;for(let d=0;d<a.length;d++){const e=a[d].getElementsByTagName("input");c=0;for(let f=0;f<e.length;f++)e[f].checked&&(c=Flags.set(c,Flags.toBits(f)));b[d]=c}return b}
class MyEvent{constructor(){this.eventChildIndex=-1}setEventElement(a){this.eventElement=a?-1===this.eventChildIndex?a:a.children[this.eventChildIndex]:void 0}setEvent(a,b,c,d){this.eventChildIndex="number"===typeof d?d:-1;this.setEventElement(a);this.eventType=b;this.eventCallback=c;this.eventWaiting=!0;this.eventElement&&(this.eventElement.addEventListener(this.eventType,this.eventCallback),this.eventWaiting=void 0)}resetEvent(){this.eventElement&&this.eventCallback&&this.eventElement.removeEventListener(this.eventType,
this.eventCallback);this.eventElement=void 0;this.eventWaiting=!0}updateEvent(a){this.eventWaiting&&this.eventCallback&&(this.setEventElement(a),this.eventElement&&(this.eventElement.addEventListener(this.eventType,this.eventCallback),this.eventWaiting=void 0))}}
class Component extends MyEvent{constructor(a,b,c="div",d){super();this._parent=dom.get(a);this.classNameWrapper=b;this.tagName=c;this.className=d}get parent(){return this._parent}get wrapper(){return this._wrapper=this._parent.getElementsByClassName(this.classNameWrapper)[0]}get element(){return this._element=this._parent.getElementsByClassName(this.className)[0]}updateWrapper(){this.classNameWrapper&&(this._wrapper=this.wrapper||dom.element("div",this._parent,this.classNameWrapper))}updateElement(){this._element=
this.element;this.updateWrapper();this._element||(this._element=dom.element(this.tagName,this._wrapper||this._parent,this.className),super.eventWaiting=!0);this._element=this._element||dom.element(this.tagName,this._wrapper||this._parent,this.className)}reset(){this.updateElement();this._element.innerHTML="";this._element.classList.toggle(this.className,!0);this.updateEvent(this._element)}remove(){dom.remove(this._wrapper||this._element);this.resetEvent();this._wrapper=this._element=void 0}visible(a){this.disabled||
!this._element&&!this._wrapper||((this._wrapper||this._element).style.display=a?"":"none")}setEvent(a,b,c){super.setEvent(this.element,a,b,c)}}class Breadcrumb extends Component{constructor(a="header"){super(a,"row",Breadcrumb.PROPS.tagName,Breadcrumb.PROPS.className)}render(a){super.reset();if(a)for(const b of a)b.href||(b.href="javascript:void(0)"),dom.element("a",dom.element("li",this._element),b)}addTopic(a){a&&dom.element("a",dom.element("li",this._element),{href:"#",textContent:a})}}
Breadcrumb.PROPS={className:"breadcrumb",tagName:"ul"};factory.addClass(Breadcrumb);class GoTop{constructor(){GoTop.instance=this;this.render()}render(){this.\u0435=dom.element("button",document.getElementsByTagName("main")[0],"go-top");dom.svgUse(this.\u0435,"#go-top","","30","30","img");this.visible(!1);this.\u0435.addEventListener("click",scrollTop);window.onscroll=scrollEvent}visible(a){this.\u0435&&!this.disabled&&(this.\u0435.style.display=a?"":"none")}}
function scrollTop(){document.body.scrollTop=0;document.documentElement.scrollTop=0}function scrollEvent(){GoTop.instance.visible(20<document.body.scrollTop||20<document.documentElement.scrollTop)}
class Tags extends Component{constructor(a="bottom"){super(a,null,Tags.PROPS.tagName,Tags.PROPS.className)}render(a){a=[{href:"#",textContent:"this"},{href:"#",textContent:"is"},{href:"#",textContent:"under"},{href:"#",textContent:"construction"}];super.reset();dom.text("span",this.element,"Topics",Tags.PROPS.header.className);for(const b of a)dom.element("a",dom.element("div",this.element,Tags.PROPS.item.className),b)}}Tags.PROPS={className:"tags",tagName:"div",item:{className:"tag"},header:{className:"heading"}};
factory.addClass(Tags);const NOTIFY={box:{className:"notify-box"},type:{msg:"msg",alert:"alert"},status:{info:"info",error:"error",success:"success"},prefix:{info:"Info: ",error:"Error: ",success:"Success: "},size:{small:20,normal:22,large:24},msg:{className:"msg-box",classNameItem:"item",classNameTitle:"msg-title",capacity:0,timer:0},alert:{className:"alert-box",classNameItem:"item",capacity:2,timer:1E4,ticker:1,close:1},button:{capacity:1,button:{label:"clickMe",svg:"svg_msg"}}};
NOTIFY.svg_msg={width:NOTIFY.size.normal,height:NOTIFY.size.normal,byStatus:{info:{id:"info"},success:{id:"success"},error:{id:"error"}}};NOTIFY.svg_alert={width:NOTIFY.size.normal,height:NOTIFY.size.normal,byStatus:{info:{id:"info-fill"},success:{id:"success-fill"},error:{id:"error-fill"}}};NOTIFY.button.button.svg=NOTIFY.svg_msg;
const NOTIFY_TEMPLATES={msg:{symbol_prefix_text:{callback:msg_symbol_prefix_text,options:{svg:NOTIFY.svg_msg}},title_text:{callback:msg_title_text},text:{callback:msg_text},button:{callback:msg_button,options:NOTIFY.button}},alert:{text:{callback:alert_text,options:{svg:NOTIFY.svg_alert}}}};
class Notify{constructor(a){Notify.storage={};Notify.defaultInit(a);this.type=NOTIFY.type;this.status=NOTIFY.status;this.template=NOTIFY_TEMPLATES}create(a,b,c,d,e,f){f=objects.assign({},e.options,f);Notify.storage[a]={};Notify.storage[a].parent=b;b=Notify.getBox(a);const g=new Msg(a,b,c,d,e.callback,f);Notify.storage[a].obj=g;Notify.prototype[a]=(h,k,l)=>g.render(h,k,l);return Notify.prototype[a]}with(a){return Notify.storage[a].obj}clear(){Object.values(Notify.storage).forEach(a=>a.obj.clear())}msg(a,
b,c){Notify.storage.msg.obj.render(a,b,c)}alert(a,b,c){Notify.storage.alert.obj.render(a,b,c)}btn(a,b,c,d){c=objects.assign({},NOTIFY.button,{button:{svg:{byStatus:null}}},{button:{svg:NOTIFY.button.button.svg.byStatus[a]}},d,{button:{func:c}});Notify.storage.btn.obj.render(a,b,c)}static remove(a){"object"===typeof Notify.storage[a]&&(Notify.storage[a].obj.clear(),delete Notify.storage[a])}static getBox(a){a=dom.get(Notify.storage[a].parent);return a.getElementsByClassName(NOTIFY.box.className)[0]||
dom.element("div",a,NOTIFY.box.className)}static defaultInit(a){if(a){a=Page.elements.article;var b=Page.elements.messages,c=NOTIFY_TEMPLATES.msg.symbol_prefix_text;b.classList.toggle(NOTIFY.box.className,!0);b=new Msg("msg",b,null,"msg",c.callback,c.options);Notify.storage.msg={obj:b,parent:a};a=Page.elements.header.firstChild;b=Page.elements.notify1;c=NOTIFY_TEMPLATES.alert.text;b=new Msg("alert",b,null,"alert",c.callback,c.options);Notify.storage.alert={obj:b,parent:a};a=a.nextSibling;b=Page.elements.notify2;
c=NOTIFY_TEMPLATES.msg.button;b=new Msg("btn",b,null,"msg",c.callback,c.options);Notify.storage.btn={obj:b,parent:a}}}}factory.addClass(Notify);
class Msg{constructor(a,b,c,d,e,f){this.storage=[];this.name=a;this.parent=dom.get(b);this.status=c;this.type=d;this.callback=e;this.options=objects.assign({},NOTIFY[d],f)}render(a,b,c){c=objects.assign({},this.options,c);document.body.contains(this.parent)||(this.parent=Notify.getBox(this.name));0<c.capacity&&this.storage.length>=c.capacity&&dom.remove(this.storage.shift());0<c.timer&&(this.timeout=c.timer/1E3,this.ticker=this.ticker||setInterval(this.tick.bind(this),1E3));a=this.callback(this.parent,
a||this.status,b,c);c.close&&dom.svgUse(dom.element("span",a,"btn-close"),"#close-button","","24","24","button").addEventListener("click",this.clear.bind(this));this.storage.push(a)}tick(){1>--this.timeout&&this.clear();this.options.ticker&&this.update()}update(){this.storage.forEach(a=>{(a.getElementsByClassName("ticker")[0]||dom.element("small",a,"ticker")).textContent=this.timeout})}clear(){const a=this.storage.length;for(let b=0;b<a;b++)dom.remove(this.storage.shift());this.ticker&&(clearInterval(this.ticker),
this.ticker=null)}}function msg_symbol_prefix_text(a,b,c,d){let {prefix:e,classNameItem:f}=d;e=e?e:""===e?"":NOTIFY.prefix[b];a=notify_box(a,null,d);notify_svg(a,b,d);b=dom.element("small",a,f);e&&dom.text("strong",b,e);c&&dom.text("small",a,c,f);return a}function msg_title_text(a,b,c,d){const {title:e,data:f}=c||{};a=notify_box(a,null,d);d=dom.element("div",a,d.classNameTitle);dom.node(e,dom.element("p",d));d=dom.element("ul",d);for(const g of f)dom.node(g,dom.element("li",d));return a}
function msg_text(a,b,c,d){a=notify_box(a,null,d);dom.text(d.tag||"strong",a,c,d.classNameItem);return a}function msg_button(a,b,c,d){const {svg:e,tag:f,label:g,func:h}=d.button;a=notify_box(a,null,d);dom.setOptions(a,{role:"button"});e&&notify_svg(a,b,d);b=dom.element("span",a,d.classNameItem);dom.text(f||"strong",b,c||g);a.addEventListener("click",h);return a}function alert_text(a,b,c,d){a=notify_box(a,b,d);notify_svg(a,b,d);dom.text(d.tag||"span",a,c,d.classNameItem);return a}
function notify_box(a,b,c){return dom.element("div",a,c.className+(b?" "+b:""))}function notify_svg(a,b,c){const {hideSvg:d,classNameItem:e}=c;if(!d){c=objects.assign({},c.svg||c.button.svg);if(c.byStatus){const m=objects.assign({},c);objects.assign(c,c.byStatus[b],m)}var {id:f,width:g,height:h,color:k,className:l}=c;if(f)return a=dom.svgUse(a,"#"+f,e,g,h),l&&a.classList.toggle(l,!0),k&&(a.style.color=k),a}}
const BAR={className:"bar",tagName:"div",elements:{},initElements:()=>{BAR.elements.start=document.getElementById("start");BAR.elements.onPlay={};BAR.elements.onPlay.back=document.getElementById("back");BAR.elements.onPlay.row=document.getElementById("row");BAR.elements.onPlay.forward=document.getElementById("forward");BAR.elements.onPlay.shuffle=document.getElementById("shuffle");BAR.elements.tabs=document.getElementById("tabs")}};
class Bar extends Component{constructor(a="control"){super(a,null,BAR.tagName,BAR.className);this.tabs=[]}render(a){super.reset();renderDom(this._element);BAR.initElements();this.json=a;this.tabs.length=0;this.activeTabs=this.json.state.tabs;this.onPlay(!1);BAR.elements.onPlay.row.disabled=!0;for(a=0;a<this.activeTabs.length;a++)this.tabs.push(dom.element("button",BAR.elements.tabs,{key:a,textContent:this.json.labels[a]})),this.setActiveTab(a,!0)}start(){this.json.state.status="start";this.setLabel(BAR.elements.start,
"Stop");this.setActive(BAR.elements.start,!0);this.onPlay(!0);this.resetTabs(!0)}stop(){this.json.state.status="stop";this.setLabel(BAR.elements.start,"Start");this.setActive(BAR.elements.start,!1);this.onPlay(!1);this.resetTabs()}resetTabs(a){for(let b=0;b<this.activeTabs.length;b++)this.setActiveTab(b,a?b!==this.json.state.card:!0)}toggle(a){this.setActiveTab(a,!this.activeTabs[a])}setActiveTab(a,b){this.setActive(this.tabs[a],b);this.activeTabs[a]=b}shuffle(a){this.setActive(BAR.elements.onPlay.shuffle,
a)}onPlay(a){Object.values(BAR.elements.onPlay).forEach(b=>b.style.display=a?"":"none")}get row(){return BAR.elements.onPlay.row.children[0].textContent}set row(a){BAR.elements.onPlay.row.children[0].textContent=a||"0"}setActive(a,b=!0){a.classList.toggle("active",b)}setLabel(a,b){a.textContent=b}isActive(a){return this.activeTabs[a]}getTabIndex(a){return parseInt(a.getAttribute("key"))}}factory.addClass(Bar);
function renderDom(a){a.innerHTML='\x3cdiv class\x3d"buttons"\x3e\n        \x3cbutton id\x3d"start"\x3eStart\x3c/button\x3e\n        \x3cbutton id\x3d"back"\x3e\n            \x3csvg viewBox\x3d"0 0 32 32" width\x3d"15" height\x3d"15" fill\x3d"none" stroke\x3d"currentColor" stroke-linecap\x3d"round" stroke-linejoin\x3d"round" stroke-width\x3d"4"\x3e\n                \x3cpath d\x3d"M20 30 L8 16 20 2"/\x3e\n            \x3c/svg\x3e\n        \x3c/button\x3e\n        \x3cbutton id\x3d"row" disabled\x3e\x3csmall\x3e\x3c/small\x3e\x3c/button\x3e\n        \x3cbutton id\x3d"forward"\x3e\n            \x3csvg viewBox\x3d"0 0 32 32" width\x3d"15" height\x3d"15" fill\x3d"none" stroke\x3d"currentColor" stroke-linecap\x3d"round" stroke-linejoin\x3d"round" stroke-width\x3d"4"\x3e\n                \x3cpath d\x3d"M12 30 L24 16 12 2"/\x3e\n            \x3c/svg\x3e\n        \x3c/button\x3e\n    \x3c/div\x3e\n    \x3cdiv class\x3d"toggles"\x3e\n        \x3cbutton id\x3d"shuffle"\x3e\n            \x3csvg xmlns\x3d"http://www.w3.org/2000/svg" viewBox\x3d"0 0 24 24" width\x3d"14" height\x3d"14" stroke\x3d"currentColor" stroke-width\x3d"1.5" stroke-linecap\x3d"round" stroke-linejoin\x3d"round" fill\x3d"none" shape-rendering\x3d"geometricPrecision"\x3e\n                \x3cpath d\x3d"M16 3h5v5"/\x3e\x3cpath d\x3d"M4 20L21 3"/\x3e\x3cpath d\x3d"M21 16v5h-5"/\x3e\x3cpath d\x3d"M15 15l6 6"/\x3e\x3cpath d\x3d"M4 4l5 5"/\x3e\n            \x3c/svg\x3e\n        \x3c/button\x3e\n    \x3c/div\x3e\n    \x3cdiv class\x3d"toggles"\x3e\n        \x3cdiv class\x3d"toggles" id\x3d"tabs"\x3e\n        \x3c/div\x3e\n        \x3cbutton class\x3d"bar-menu" disabled\x3e\n            \x3csvg width\x3d"14" height\x3d"14" viewBox\x3d"0 0 24 24" width\x3d"15" height\x3d"15" alt\x3d"menu"\x3e\n                \x3cpath d\x3d"M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z" fill\x3d"currentColor"/\x3e\n            \x3c/svg\x3e\n        \x3c/button\x3e\n    \x3c/div\x3e'}
const CARDS={maskCharacter:"_",className:"cards",tagName:"div"};
class Cards extends Component{constructor(a="content"){super(a,null,CARDS.tagName,CARDS.className);this.cards=[];this.active=-1}render(a){this.json=a;this.reset();for(a=0;a<this.json.state.tabs.length;a++)this.createCard(this.element);this.setActive(this.json.state.card)}setActive(a){-1<this.active&&this.cards[this.active].classList.toggle("active",!1);this.active=this.json.state.card=a;this.cards[this.active].classList.toggle("active",!0)}populate(a){"number"===typeof a&&(this.json.state.row=a);
this.words=this.json.data[this.json.state.row];for(a=0;a<this.cards.length;a++)this.setContent(a,this.words?this.words[a]:"");this.update()}setContent(a,b){this.cards[a].firstChild.textContent=b}setStatus(a,b){this.cards[this.active].classList.toggle(a,b);this.cards[this.active].classList.toggle("active",!b);this.status=b?a:null}update(a){if(-1!==this.active&&this.element)if("number"===typeof a)this.updateIndex(a);else for(a=0;a<this.cards.length;a++)this.updateIndex(a)}updateIndex(a){const b=this.json.state.tabs[a];
a===this.active?(this.visibleContent(a,!0),b||"error"===this.status?this.setContent(a,this.words[a]):this.setContent(a,strings.mask(this.words[a],CARDS.maskCharacter))):this.visibleContent(a,b)}createCard(a){const b=this.cards.length||0;a=dom.element("div",a);a.id="card"+(b+1);a.classList.add("card");dom.element("h4",a);this.cards.push(a)}isValid(){return-1<this.active&&this.cards.length>this.active}visibleContent(a,b){this.cards[a].firstChild.style.visibility=b?"":"hidden"}reset(){super.reset();
this.cards.length=0;this.json.state.row=0;this.active=-1;this.status=null}}factory.addClass(Cards);
class Stats{constructor(){Stats.default={stats:{className:"stats right"},award:{src:"./assets/images/award.svg",alt:"award",width:"18",height:"18"},counts:{className:"counts left"}}}render(a,b){b=b||Stats.default;this.elements={};this.element=dom.element("div",a);a=dom.element("div",this.element,b.stats);this.elements.error=dom.element("small",a);this.elements.success=dom.element("small",a);dom.element("img",a,b.award);a=dom.element("div",this.element,b.counts);this.elements.done=dom.element("small",
a);dom.text("span",a,"|");this.elements.rows=dom.element("small",a);this.setStats(0,0,0,0)}getStats(){return{done:this.elements.done.textContent,rows:this.elements.rows.textContent,error:this.elements.error.textContent,success:this.elements.success.textContent}}setStats(a,b,c,d){this.elements.done.textContent=a;this.elements.rows.textContent=b;this.elements.error.textContent=c;this.elements.success.textContent=d}change(a,b){this.elements[a].textContent=b}plus(a){this.elements[a].textContent+=1}}factory.addClass(Stats);
class UserInput extends Component{constructor(a=CS.dom.content.id){super(a,void 0,"div","input");this.successCounter=SimpleCounter();this.errorsCounter=SimpleCounter();this.stats=new Stats;this.input=new TextInput(this);this.state={}}render(a,b){super.reset();this.json=a;dom.removeAll(this.element);this.stats.render(this.element);this.input.render(this.element);this.reset();this.controller=b||this.controller}read(){this.content=this.input.value;this.state.done=this.input.isDone();this.state.done||
(this.state.error=!this.contained(this.content,this.word),this.state.success=this.compare(this.content,this.word));this.update();this.state.done&&this.controller(this)}next(){this.clear();this.words=this.json.data[this.json.state.row];this.word=this.words[this.json.state.card];this.input.setAssert(this.word);this.input.keyboard&&this.input.keyboard.renderKeys(this.word)}repeat(){this.clear();this.state.repeat=!0;notify.msg("error",CS.msg.input.again,{prefix:""});this.input.textarea.placeholder=CS.msg.input.again}reset(){this.clear();
this.successCounter.reset();this.errorsCounter.reset();this.stats.setStats(0,this.json.state.rows,0,0)}clear(){for(const a of Object.keys(this.state))this.state[a]=null;this.input.clear();notify.clear()}update(){this.state.done?(this.state.error=!this.state.success,this.state.repeat||(this.state.success?this.stats.change("success",this.successCounter.next()):this.stats.change("error",this.errorsCounter.next()),!this.state.examples&&Array.isArray(this.words.slice(-1)[0])&&(this.state.examples=this.words.slice(-1)[0],
notify.title({title:"Examples",data:this.state.examples})))):(this.input.setStatus(this.state.success?"success":this.state.error?"error":""),this.state.success&&(notify.clear(),notify.msg("info","",{prefix:"Done.",timer:2E3})))}visible(a){this.element.style.display=a?"":"none";a&&this.input.focus()}compare(a,b){return a===b}contained(a,b){return a===b.substr(0,a.length)}remove(){super.remove()}}factory.addClass(UserInput);
class TextInput{constructor(a){TextInput.default={form:{className:"form",spellcheck:"false",autocapitalize:"none",autocomplete:"off"},textarea:{placeholder:CS.msg.input.placeholder}};this.controller=a;this.opt=Object.assign({},TextInput.default)}render(a,b={}){Object.assign(this.opt,b);this.form=dom.element("form",a,this.opt.form);this.textarea=dom.element("textarea",this.form,this.opt.textarea);this.textarea.addEventListener("input",this);this.keyboard=(new MyKeyboard(this)).render(a,this.textarea,
null);this.clear()}handleEvent(a){this.assert()||(this.setStatus(""),this.controller.read())}get value(){return this.textarea.value||""}setStatus(a){this.status!==a&&(this.status=a||"",this.textarea.className=this.status+(this.keyboard.opt.mode.off?"":" active"))}clear(){this.status="";this.textarea.value="";this.textarea.placeholder=this.opt.textarea.placeholder}focus(){this.keyboard.opt.mode.off&&this.textarea.focus()}isDone(){return["\n","\r"].includes(this.value.slice(-1))}setAssert(a){this.text=
a}assert(){return this.text?(this.text=this.value.length<this.text.length?this.text:null)&&!this.status&&this.text.startsWith(this.value):null}}const KEYBOARDS={german:{small:"q w e r t z u i o p ü ß \x3c-- a s d f g h j k l ö ä # Enter _^ y x c v b n m , . - ! ?".split(" "),big:"Q W E R T Z U I O P Ü ~ \x3c-- A S D F G H J K L Ö Ä ' Enter _^ Y X C V B N M ; : _ ! ?".split(" ")}};
class MyKeyboard{constructor(a,b){MyKeyboard.instance=this;MyKeyboard.default={keys:KEYBOARDS.german,className:"keyboard",classNameItem:"item",classNameLong:"item-long",classNameOther:"other",buttons:{Enter:"\n","\x3c--":"del",__:" ","_^":"shift"},mode:{off:0===CS.app.keyboard,static:1===CS.app.keyboard,byString:2===CS.app.keyboard,size:0}};this.controller=a;this.textarea=b;this.opt=Object.assign({},MyKeyboard.default)}render(a,b,c){Object.assign(this.opt,c);this.textarea=b||this.textarea;this.modeButton=
dom.element("span",a,{id:"keyboard",role:"button",className:"right"});this.modeButton.addEventListener("click",this.changeMode);this.keyboard=dom.element("div",a,this.opt.className);this.keyboard.addEventListener("click",this);this.setMode("");return this}renderKeyboard(a){if(!this.opt.mode.off&&this.opt.mode.static){this.clear();var b=0;(a?this.opt.keys.big:this.opt.keys.small).forEach(d=>{if(0===b||0===b%13)c=dom.element("div",this.keyboard);dom.element("button",c,{index:b,textContent:d,value:1===
d.length?d:this.opt.buttons[d],type:"button",role:"button",className:this.opt.classNameItem});b++});var c=dom.element("div",this.keyboard,this.opt.classNameOther);dom.element("button",c,{textContent:" ",value:" ",type:"button",role:"button",className:this.opt.classNameItem})}}renderKeys(a){if(!this.opt.mode.off&&!this.opt.mode.static&&a){this.clear();var b=dom.element("div",this.keyboard),c=this.opt.keys,d=c.small.length,e={};for(var f of a.split(""))a=c.small.indexOf(f),a=-1<a?a:c.big.indexOf(f),
a=-1<a?a:d,e[f]=a;f=this.opt.mode.size-Object.keys(e).length;for(a=0;a<f;){const g=numbers.getRandomInt(0,d),h=c.small[g];e[h]||(e[h]=g,a++)}e["\x3c--"]=d+2;e.Enter=d+3;Object.entries(e).sort((g,h)=>g[1]-h[1]).map(g=>g[0]).forEach(g=>{dom.element("button",b,{textContent:g,value:1===g.length?g:this.opt.buttons[g],type:"button",role:"button",className:this.opt.classNameItem})})}}handleEvent(a){if(a.target.value){a=a.target.value;if(2<a.length)if("del"===a)this.textarea.value=this.textarea.value.slice(0,
-1);else{this.isBig=!this.isBig;this.renderKeyboard(this.isBig);return}else this.textarea.value+=a;this.controller.handleEvent()}}setMode(a){const b=MyKeyboard.instance.opt.mode;a=a||(b.static?"static":b.byString?"byString":"off");const c=MyKeyboard.instance.modeButton;b.off="off"===a;b.static="static"===a;b.byString="byString"===a;MyKeyboard.instance.textarea.classList.toggle("active",!b.off);CS.app.keyboard=b.off?0:b.static?1:2;"off"===a?(MyKeyboard.instance.clear(),c.textContent=CS.msg.keyboard.off):
"static"===a?(MyKeyboard.instance.renderKeyboard(),c.textContent=CS.msg.keyboard.static):"byString"===a&&(MyKeyboard.instance.renderKeys(MyKeyboard.instance.controller.text),c.textContent=CS.msg.keyboard.byString)}changeMode(a){const b=MyKeyboard.instance,c=b.opt.mode;b.setMode("string"===typeof a?a:c.off?"static":c.static?"byString":"off")}clear(){this.keyboard.innerHTML=""}}
class List extends Component{constructor(a="content"){List.default={className:"lists",tagName:"table"};super(a,null,List.default.tagName,List.default.className);this.i=this}async render(a,b){super.reset();this.json=a;this.cols=this.json.state.tabs.length;(this.opt=b)&&this.opt.contenteditable?(this.numbering=!0,this.cols++,dom.setOptions(this.element,{spellcheck:"false",autocapitalize:"none",autocomplete:"off"}),this.element.classList.toggle("numbering",!0)):(this.element.classList.toggle("numbering",
!1),this.numbering=void 0);List.renderRows(this.element,this.cols,this.json.data,this.numbering,this.opt)}update(a){if(this.element&&this.json)if("number"===typeof a)List.visibleColumn(this.element,a,this.json.state.tabs[a]);else for(a=0;a<this.cols;a++)List.visibleColumn(this.element,a,this.json.state.tabs[a])}isValidRow(a){return Number.isInteger(a)&&-1<a&&a<this.json.data.length}isFilled(a){for(let b=0;b<a.length;b++)if(strings.isBlank(a[b].textContent))return!1;return!0}read(){if(!this.element||
!this.element.rows.length)return[];const a=this.element.rows.length,b=this.element.rows[0].cells.length,c=[],d=[];for(let e=0;e<a;e++){const f=Array(b),g=this.element.rows[e].cells;if(this.isFilled(g)){for(let h=0;h<b;h++)f[h]=g[h].textContent||"";c.some(h=>List.equals(h,f,this.numbering))||c.push(f)}else d.push(this.element.rows[e])}d.forEach(e=>dom.remove(e));return c}add(){List.renderRow(this.element,this.cols,this.numbering?[this.element.rows.length+1]:[],this.opt)}static equals(a,b,c){if(a&&
b){c=c?1:0;const d=b.slice(c);return a.slice(c).every((e,f)=>e===d[f])}}static renderRow(a,b,c,d){a=dom.element("tr",a);for(let e=0;e<b;e++)dom.text("th",a,c[e]||"",d)}static renderRows(a,b,c,d,e){let f=1;for(const g of c||[])c=d?[f++,g].flat():g,List.renderRow(a,b,c,e)}static visibleColumn(a,b,c){a=a.getElementsByTagName("tr");for(let d=0;d<a.length;d++)a[d].children[b].style.display=c?null:"none"}coloredTable(a){super.reset();for(const b of a){const c=dom.element("tr",this.element);b.name&&(dom.text("th",
c,b.name),b.colors.forEach(d=>{dom.text("th",c,d).style.backgroundColor=d}))}}}factory.addClass(List);
class Menu{constructor(a){this.element=a;this.element.addEventListener("click",this);this.active=void 0}click(a){this.setActive(this.active,!1);this.setActive(a.parentNode,!0)}setActive(a,b){a&&a.classList.toggle("active",b);this.active=b?a:null}navigateByIndex(a){this.click(this.element.querySelector(`a[value = "${a}"]`))}async handleEvent(a){"click"===a.type&&await this.onclick(a.target)}async onclick(a){a&&"A"===a.tagName&&a.hasAttribute("value")&&(this.click(a),await router.navigate(parseInt(a.getAttribute("value"))))}}
class Topics{constructor(){this.element=document.getElementsByTagName("aside")[0]}async render(a="cards"){if(this.lastPage!==a){this.element.innerHTML="";var b=CS.app.isStatic?"":`?lang=${CS.app.lang}`;try{const c=await data.getJson(`${a}${b}`,!0,!1);for(const d of c)this.renderTopic(this.element,d);this.lastPage=a}catch{this.element.innerHTML='\x3cul\x3e\x3cimg src\x3d"./assets/images/loaders/puff.svg" alt\x3d"loader" width\x3d"60" height\x3d"60"\x3e\x3c/img\x3e\x3c/ul\x3e'}}}renderTopic(a,b){const c=
dom.element("ul",a),d=b.api||"";dom.text("h3",c,b.category);b.links.forEach(e=>this.renderLink(c,`${d}${e.id}`,e.text))}renderLink(a,b,c){dom.text("a",dom.element("li",a),c,{href:"javascript:void(0)",value:b})}}
factory.init=async()=>{const a=new Data,b=new Router,c=new Page,d=new Topics,e=new Notify(!0);if(!c.elements.control)return e.alert("error","This part of the static version is under construction."),{};const f={top:new Menu(document.getElementsByClassName("navbar")[0])};new GoTop;Router.exercise=new Exercise;factory.addEvent("Breadcrumb","click",Router.navigateEvent);factory.addEvent("Bar","click",Exercise.controlEvent);const g=await factory.getInstance("Breadcrumb");c.elements.aside.addEventListener("click",
Exercise.renderEvent);return{data:a,page:c,topics:d,breadcrumb:g,router:b,navigation:f,notify:e}};


const MAPS = {
    path: "./components/maps/"
}

class Maps {
    constructor(parent = "content") {
        this.parent = dom.get(parent)
    }
    async render(jsonFile) {
        const maps = Object.entries(jsonFile.props).sort(((a, b) => a[1].localeCompare(b[1]))).map(v => v[0]);
        const [name, file1, file2] = maps;

        let imp;
        const map = new Map(this.parent);

        // dynamic import - map
        imp = await import(MAPS.path + encodeURIComponent(file1));  // "./components/maps/maps-de.js"
        const res1 = imp.default;

        await map.render(res1[name]);
        map.renderInfo(res1.meta);

        // dynamic import - full data
        imp = await import(MAPS.path + encodeURIComponent(file2)); // "./components/maps/maps-de-full.js"
        const res2 = imp.default;
        map.meta = res2[name].meta;
    }

    stop() {
        // required from exercise.js
    }
    reset() {
        this.parent.innerHTML = "";
    }
}
factory.addClass(Maps)


class Map {
    constructor(parent) {
        this.wrapper = dom.element("div", parent, "row maps");
        this.element = dom.element("div", this.wrapper);
        this.info = dom.element("div", this.wrapper, "column");

        this.element.addEventListener("click", this);
    }
    async render(obj) {
        this.reset();
        this.element.innerHTML = obj.svg;
        this.meta = obj.meta;
    }
    renderInfo(meta) {
        this.info.innerHTML = "";
        dom.element("div", this.info).innerHTML = meta.flag || meta.coat_of_arms;
        dom.text("h3", this.info, `${meta.state} (${meta.ISO3166_2})`);
        dom.element("div", this.info).innerHTML = `<strong>Fläche</strong> : ${meta.area} km<sup>2</sup>`;
        dom.element("div", this.info).innerHTML = `<strong>Einwohner (2018)</strong> : ${numberWithCommas(meta.population)} Mio.`;

        this.textElement = this.textElement || document.getElementById("map-text");
        this.textElement.textContent = meta.state;
    }
    reset() {
        this.textElement = null
        this.element.innerHTML = "";
        this.info.innerHTML = "";
    }
    setActive(e) {
        if (e && this.active) {
            this.active.classList.toggle("active", null)
        }
        if (e) {
            e.classList.toggle("active", true);
        }
        this.active = e
    }
    navigateByIndex(index) {
        this.setActive(this.element.getElementById(index))
    }
    handleEvent(e) {
        const t = e ? e.type : null;
        if (t === "click") {
            this.onclick(e.target)
        }
    }
    onclick(e) {
        if (e.tagName === "path") {
            this.setActive(e);
            this.renderInfo(this.meta[Number.parseInt(e.id)])
        }
    }
}

function numberWithCommas(x) {
    return x >= 1000 ? x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") : "0," + x;
}


/**
 *  Extracted from 'factory_loader.js' for easy gradle.build
 *
 * @param className
 * @returns {Promise<object>}
 */
async function getInstance(className) {

    let clazz = factory.instance(className);

    if (!clazz) {
        let {Clazz, parent, path, eventType, event} = factory.props(className)

        if (Clazz) {
            /**   create instance from class               (default parent) */
            clazz = new Clazz()
            // console.debug("create instance from Class: " + className)

        } else if (path) {
            /**   dynamic import, then create instance     (default parent) */
                // await sleep(1000)
            const obj = await import(path)
            Clazz = obj[className] || obj["default"];
            clazz = new Clazz()
            // console.debug("import class and create instance: " + path)
        }
        /**   update event and factory storage              */
        if (clazz) {
            if (event) {
                clazz.setEvent(eventType, event)
            }
            factory.addInstance(className, clazz)
        } else {
            console.error("unable to create instance: " + className)
        }
    }
    // console.debug("get instance: " + name)
    return clazz;
}

/*
async function sleep(milliseconds) {
    const date = Date.now();
    let currentDate = null;
    do {
        currentDate = Date.now();
    } while (currentDate - date < milliseconds);
    console.debug(`sleep: ${milliseconds}`);
}
*/

const {data, page, topics, breadcrumb, router, navigation, notify} = await factory.init();export {router}